dist: trusty
language: node_js

node_js:
  - lts/*

env:
  - SKIP_CHECK=true

cache:
  directories:
    - node_modules

before_install:
  - node --version

install:
  - npm install -g npm@6.1.0
  - npm ci
  - npm audit

before_script:
  - npm run bootstrap
  - npm run build

script:
  - npm run test --ci --runInBand

jobs:
  include:
    - stage: Test # test for lts/*
    - stage: Test
      node_js:
        - node

    - stage: Coding standard
      script:
        - npm run lint:eslint:source
        - npm run lint:eslint:supporting
        - npm run lint:style

    - stage: Coverage
      script:
        - npm install -g codecov
        - npm run test:coverage --ci --runInBand
        - codecov

    - stage: Release
      if: branch = master
      script:
        - |
          git config --global user.email "$GH_USER_EMAIL"
          git config --global user.name "$GH_USER_NAME"
          git config credential.helper "store --file=.git/credentials";
          echo "https://$GH_TOKEN:@github.com" > .git/credentials;
        - chmod a+x ./build/ping-npm.sh
        - bash ./build/ping-npm.sh
        - yarn lerna exec --concurrency 1 "npx --no-install semantic-release -e semantic-release-monorepo" && node -e "require('semantic-release-monorepo-hooks').hookAfterAll()"


notifications:
  email:
    on_success: never
    on_failure: change
