dist: trusty
language: node_js

node_js:
  - lts/*

env:
  - SKIP_CHECK=true

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - node --version && yarn --version

install:
  - yarn --frozen-lockfile

before_script:
  - yarn run bootstrap
  - yarn run build

script:
  - yarn run test --ci --runInBand

jobs:
  include:
    - stage: Test # test for lts/*
    - stage: Test
      node_js:
        - node

    - stage: Coding standard
      script:
        - yarn run lint:eslint:source
        - yarn run lint:eslint:supporting
        - yarn run lint:style

    - stage: Coverage
      script:
        - yarn global add codecov
        - yarn test:coverage --ci --runInBand
        - codecov

notifications:
  email:
    on_success: never
    on_failure: change
